"""Render ``reports/env_matrix.md`` from the smoke run's measurements.

Kept separate from ``smoke.py`` so the report can be regenerated without
re-running a GPU job, and so the numbers in the committed markdown always come
from a JSON artifact rather than from prose someone typed by hand.
"""

from __future__ import annotations

import json
from typing import Any

from ragft.settings import REPO_ROOT


def render(results: dict[str, Any]) -> str:
    v = results["versions"]
    c = results["config"]
    m = results["measurements"]
    g = results["gpu"]
    p = results["params"]
    proj = results["projection"]

    total = g.get("total_gib", 0.0)
    headroom_pct = 100 * m["headroom_gib"] / total if total else 0.0

    return f"""# Environment matrix

Generated by `scripts/00_smoke.sh` from `reports/smoke_results.json`.
**Do not hand-edit** — rerun the smoke job instead.

Measured `{results["measured_at"]}` on `{results["host"]}`.

## Verdict: {results["verdict"]}

The pinned matrix loads Qwen2.5-7B in 4-bit NF4, attaches LoRA to all seven
projections, and takes real optimizer steps on this GPU.

## Why this file exists

The dependency conflict below is real and was present in this machine's base
environment before the project started:

| Package | Constraint |
|---|---|
| `bitsandbytes {v["bitsandbytes"]}` | requires `transformers<5` |
| `trl {v["trl"]}` | requires `transformers>=4.56.2` |
| **Satisfiable window** | **`transformers>=4.56.2,<5`** |
| Base env on this machine | `transformers 5.14.1` on Python 3.13 — **outside the window** |

That is why this project uses its own `uv` venv pinned to Python 3.11.

## Verified versions

| Component | Version |
|---|---|
| Python | {v["python"]} |
| torch | {v["torch"]} (CUDA build {v["cuda_build"]}) |
| transformers | {v["transformers"]} |
| peft | {v["peft"]} |
| trl | {v["trl"]} |
| bitsandbytes | {v["bitsandbytes"]} |
| accelerate | {v["accelerate"]} |

## Hardware

| Property | Value |
|---|---|
| GPU | {g["name"]} |
| Compute capability | {g["compute_capability"]} |
| Total VRAM | {g["total_gib"]} GiB |
| bf16 supported | {g["bf16_supported"]} |

No SLURM on this host — verified absent: `sbatch`, `squeue`, `sinfo`, module
system, and any cluster entry in `~/.ssh/config`. Jobs run under tmux via
`scripts/run.sh`.

## Configuration measured

| Setting | Value |
|---|---|
| Model | `{c["model"]}` |
| Quantization | {c["quant"]} |
| LoRA rank / alpha | {c["lora_r"]} / {c["lora_alpha"]} |
| Target modules | {", ".join(f"`{t}`" for t in c["target_modules"])} |
| Sequence length | {c["seq_len"]} |
| Batch (per-device x accum = effective) | {c["per_device_batch"]} x {c["grad_accum"]} = {c["effective_batch"]} |
| Gradient checkpointing | {c["gradient_checkpointing"]} |
| Optimizer | `{c["optim"]}` |
| Packing | {c["packing"]} |

Trainable parameters: **{p["trainable"]:,}** of {p["total"]:,} (**{p["trainable_pct"]}%**).

## Measurements

| Metric | Value |
|---|---|
| Model load time | {m["model_load_seconds"]} s |
| Weights only (4-bit, post-load) | {m["weights_only_gib"]} GiB |
| **Peak allocated** | **{m["peak_allocated_gib"]} GiB** |
| **Peak reserved** | **{m["peak_reserved_gib"]} GiB** |
| Headroom on a {g["total_gib"]} GiB card | {m["headroom_gib"]} GiB ({headroom_pct:.0f}%) |
| Mean step time (warmup discarded) | {m["mean_step_seconds"]} s |
| Steps timed | {m["steps_timed"]} |
| **Throughput** | **{m["tokens_per_second"]} tokens/s** |
| Final loss | {m["final_loss"]} |

Headroom matters more than speed here: this GPU is shared, so a run that peaks
near capacity is a run that dies when someone else allocates memory.

## Recalibrated compute budget

Projected from measured throughput, assuming {proj["assumed_train_examples"]:,}
training examples averaging **{proj["assumed_avg_tokens_per_example"]} tokens each**.

⚠️ The average example length — not `seq_len` — drives this. With packing on,
short examples are concatenated to fill each {c["seq_len"]}-token block, so
{proj["assumed_train_examples"]:,} examples of ~{proj["assumed_avg_tokens_per_example"]}
tokens occupy roughly {proj["tokens_per_epoch"] // c["seq_len"]:,} sequences, not
{proj["assumed_train_examples"]:,} of them. Using `examples x seq_len` instead
overstates the budget by the packing ratio (~{c["seq_len"] / proj["assumed_avg_tokens_per_example"]:.1f}x here).

The token count itself is still an **estimate** until Phase 1 measures the real
length distribution of (passage + question + formatted answer). Throughput is
measured; the example length is not, yet.

| Item | GPU-hours |
|---|---|
| One epoch | {proj["hours_per_epoch"]} |
| One 3-epoch run | {proj["hours_per_3epoch_run"]} |
| Sweep: 4 configs x 1 epoch | {proj["sweep_4_configs_1_epoch"]} |
| Final: 3 seeds x 3 epochs | {proj["final_3_seeds_3_epochs"]} |
| **Training total** | **{proj["training_total"]}** |

Evaluation, latency measurement and the smoke job add roughly 4.5 GPU-hours on
top, and are dominated by generation rather than training.
"""


def main() -> None:
    reports = REPO_ROOT / "reports"
    src = reports / "smoke_results.json"
    if not src.exists():
        raise SystemExit(f"{src} not found — run scripts/00_smoke.sh first.")
    results = json.loads(src.read_text(encoding="utf-8"))
    out = reports / "env_matrix.md"
    out.write_text(render(results), encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
