"""Across-seed variance for the fine-tuned arms. Phase 6.

Single-run numbers are this genre's most common credibility failure: a 4.6-point
gap between two arms means nothing until you know the run-to-run spread. This
reports mean +/- std over seeds for every judge-free metric, and -- the part that
actually settles the question -- whether the A4-over-A2 gap survives the spread.

Only the FINE-TUNED arms vary with seed. A1 and A2 use no adapter and run under
greedy decoding, so they are deterministic given the same checkpoint and prompt;
re-running them per seed would burn GPU-hours reproducing identical numbers.
That asymmetry is why the comparison below is "A4 seeds vs the single A2 value"
rather than a difference of two distributions.

Reads `data/eval/responses/{arm}__{tag}.jsonl` plus the untagged seed-42 files.

Usage::

    uv run python -m ragft.analysis.seeds
"""

from __future__ import annotations

import json
import re
import statistics
from typing import Any

from ragft.eval.metrics.citation import aggregate as citation_aggregate
from ragft.settings import REPO_ROOT

RESPONSES = REPO_ROOT / "data" / "eval" / "responses"
REPORTS = REPO_ROOT / "reports"

FT_ARMS = ("A3_ft_zeroshot", "A4_ft_rag")
BASE_ARMS = ("A1_base_zeroshot", "A2_base_rag")
METRICS = ("section_correct_rate", "act_correct_rate", "fabrication_rate")


def _score(path: Any) -> dict[str, Any]:
    rows = [json.loads(line) for line in path.open(encoding="utf-8") if line.strip()]
    return citation_aggregate(
        [r["response"] for r in rows], [r["source_section_ids"] for r in rows]
    ) | {"n": len(rows)}


def collect() -> dict[str, dict[str, dict[str, Any]]]:
    """arm -> seed -> metrics. The untagged file is seed 42 by convention."""
    out: dict[str, dict[str, dict[str, Any]]] = {}
    for arm in FT_ARMS:
        per_seed: dict[str, dict[str, Any]] = {}
        base = RESPONSES / f"{arm}.jsonl"
        if base.exists():
            per_seed["42"] = _score(base)
        for path in sorted(RESPONSES.glob(f"{arm}__seed*.jsonl")):
            m = re.search(r"__seed(\w+)\.jsonl$", path.name)
            if m:
                per_seed[m.group(1)] = _score(path)
        if per_seed:
            out[arm] = per_seed
    return out


def build() -> dict[str, Any]:
    per_seed = collect()
    if not per_seed:
        raise SystemExit("No fine-tuned responses found.")

    summary: dict[str, Any] = {}
    for arm, seeds in per_seed.items():
        entry: dict[str, Any] = {"seeds": sorted(seeds), "n_seeds": len(seeds)}
        for metric in METRICS:
            vals = [seeds[s][metric] for s in sorted(seeds)]
            entry[metric] = {
                "per_seed": dict(zip(sorted(seeds), vals, strict=True)),
                "mean": round(statistics.mean(vals), 4),
                # Sample std is undefined for one value. Reporting 0.0 there
                # would assert zero variance from a single observation, which is
                # exactly the false confidence this module exists to remove.
                "std": round(statistics.stdev(vals), 4) if len(vals) > 1 else None,
            }
        summary[arm] = entry

    # The question the whole run exists to answer.
    verdict: dict[str, Any] = {}
    a2_path = RESPONSES / "A2_base_rag.jsonl"
    if a2_path.exists() and "A4_ft_rag" in summary:
        a2 = _score(a2_path)["section_correct_rate"]
        a4 = summary["A4_ft_rag"]["section_correct_rate"]
        vals = list(a4["per_seed"].values())
        worst = min(vals)
        verdict = {
            "comparison": "A4_ft_rag vs A2_base_rag, correct-section rate",
            "a2_single_run": a2,
            "a4_per_seed": a4["per_seed"],
            "a4_mean": a4["mean"],
            "a4_std": a4["std"],
            "mean_gap": round(a4["mean"] - a2, 4),
            "worst_seed_gap": round(worst - a2, 4),
            "every_seed_beats_a2": bool(worst > a2),
            "n_seeds": len(vals),
        }
        if a4["std"] is not None:
            # Not a significance test -- with 3 seeds it cannot be. It asks the
            # weaker, honest question: is the gap larger than the spread?
            verdict["gap_exceeds_1_std"] = bool((a4["mean"] - a2) > a4["std"])

    payload = {"per_arm": summary, "verdict": verdict}
    REPORTS.mkdir(parents=True, exist_ok=True)
    (REPORTS / "seeds.json").write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    (REPORTS / "seeds.md").write_text(render(payload), encoding="utf-8")
    return payload


def _fmt(entry: dict[str, Any]) -> str:
    if entry["std"] is None:
        return f"{entry['mean']:.1%} (1 seed)"
    return f"{entry['mean']:.1%} ± {entry['std'] * 100:.1f}"


def render(p: dict[str, Any]) -> str:
    lines = [
        "# Across-seed variance",
        "",
        "Generated by `ragft.analysis.seeds`. **Do not hand-edit.**",
        "",
        "Only the fine-tuned arms vary with seed. A1 and A2 use no adapter and run",
        "greedy, so they are deterministic given the same checkpoint and prompt.",
        "",
        "| Arm | seeds | Correct section | Correct act | Fabrication |",
        "|---|---|---|---|---|",
    ]
    for arm, e in p["per_arm"].items():
        lines.append(
            f"| {arm} | {', '.join(e['seeds'])} | {_fmt(e['section_correct_rate'])} | "
            f"{_fmt(e['act_correct_rate'])} | {_fmt(e['fabrication_rate'])} |"
        )

    v = p.get("verdict")
    if v:
        lines += [
            "",
            "## Does A4's gain over A2 survive the seed spread?",
            "",
            "This is the question the run exists to answer. The headline claims",
            "fine-tuning adds something *on top of* retrieval, and a one-seed gap of a",
            "few points is not evidence of that.",
            "",
            f"| A2 (single run, deterministic) | {v['a2_single_run']:.1%} |",
            "|---|---|",
            f"| A4 mean over {v['n_seeds']} seed(s) | **{v['a4_mean']:.1%}**"
            + (f" ± {v['a4_std'] * 100:.1f}" if v.get("a4_std") is not None else "")
            + " |",
            f"| Mean gap | **{v['mean_gap'] * 100:+.1f} points** |",
            f"| Worst-seed gap | **{v['worst_seed_gap'] * 100:+.1f} points** |",
            f"| Every seed beats A2 | **{'yes' if v['every_seed_beats_a2'] else 'NO'}** |",
            "",
        ]
        if v.get("gap_exceeds_1_std") is False:
            lines += [
                "**The gap is smaller than the seed-to-seed spread.** On this evidence",
                "A4's advantage over A2 is not established, and the headline should be",
                "read as 'fine-tuning on top of retrieval changed little' rather than",
                "'fine-tuning helps'.",
                "",
            ]
        elif v.get("gap_exceeds_1_std") is True:
            lines += [
                "The gap exceeds one standard deviation across seeds. That is not a",
                "significance test -- three seeds cannot support one -- but it is the",
                "weaker claim the data can carry: the effect is larger than the noise",
                "that produced it.",
                "",
            ]
        if not v["every_seed_beats_a2"]:
            lines += [
                "**At least one seed does not beat A2**, which is the more damaging",
                "observation and is stated first wherever this is summarised.",
                "",
            ]
    return "\n".join(lines)


def main() -> None:
    p = build()
    for arm, e in p["per_arm"].items():
        print(f"{arm:20s} seeds={','.join(e['seeds'])} correct={_fmt(e['section_correct_rate'])}")
    if p.get("verdict"):
        v = p["verdict"]
        print(
            f"\nA4 vs A2: mean gap {v['mean_gap'] * 100:+.1f}pp, "
            f"worst seed {v['worst_seed_gap'] * 100:+.1f}pp, "
            f"every seed beats A2: {v['every_seed_beats_a2']}"
        )
    print(f"\nWrote {REPORTS / 'seeds.md'}")


if __name__ == "__main__":
    main()
