"""Hyperparameter sweep report. Phase 4, run late and deliberately.

Every number in this repo comes from rank 16 / lr 2e-4, so the honest claim has
been *"this QLoRA configuration failed at section recall"* rather than *"QLoRA
fails"*. That caveat appears in RESULTS.md and the model card.

This exists to test whether the caveat is load-bearing.

* If all four configs land in the same place, the caveat can be dropped: the
  finding survives the two axes people actually tune, and "a thin adapter cannot
  absorb ~1,090 section numbers from 2,830 examples" becomes a claim about the
  task rather than about one lucky-or-unlucky config.
* If one config is markedly better, **the headline is wrong** and has to be
  rerun on that config. That is the outcome worth spending GPU-hours to rule
  out, and it is why the sweep is worth doing even this late.

Rank 64 is the config that matters most. The project's central claim is that
section numbers are too high-cardinality for a small adapter. If that is a
*capacity* limit rather than a *data* limit, 4x the adapter parameters is where
it should show.

Usage::

    uv run python -m ragft.analysis.sweep
"""

from __future__ import annotations

import json
import statistics
from typing import Any

from ragft.eval.metrics.citation import aggregate as citation_aggregate
from ragft.settings import REPO_ROOT

OUT = REPO_ROOT / "out"
RESPONSES = REPO_ROOT / "data" / "eval" / "responses"
REPORTS = REPO_ROOT / "reports"

# The reported configuration, for reference in the table.
BASELINE = "r16_lr2e-4"


def collect() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for summary_path in sorted(OUT.glob("sweep_*/summary.json")):
        s = json.loads(summary_path.read_text(encoding="utf-8"))
        name = summary_path.parent.name.removeprefix("sweep_")
        entry: dict[str, Any] = {
            "config": name,
            "rank": s["lora_rank"],
            "learning_rate": s["learning_rate"],
            "trainable_params": s["trainable_params"],
            "eval_loss": (s["eval_loss_by_epoch"] or [{}])[0].get("eval_loss"),
            "train_loss": s["final_train_loss"],
            "minutes": s["elapsed_minutes"],
        }
        resp = RESPONSES / f"A3_ft_zeroshot__sweep_{name}.jsonl"
        if resp.exists():
            r = [json.loads(line) for line in resp.open(encoding="utf-8") if line.strip()]
            cit = citation_aggregate(
                [x["response"] for x in r], [x["source_section_ids"] for x in r]
            )
            entry |= {
                "n_eval": len(r),
                "section_correct_rate": cit["section_correct_rate"],
                "act_correct_rate": cit["act_correct_rate"],
                "fabrication_rate": cit["fabrication_rate"],
            }
        rows.append(entry)
    return rows


def build() -> dict[str, Any]:
    rows = collect()
    if not rows:
        raise SystemExit("No sweep runs found under out/sweep_*/.")

    scored = [r for r in rows if "section_correct_rate" in r]
    verdict: dict[str, Any] = {}
    if len(scored) > 1:
        sec = [r["section_correct_rate"] for r in scored]
        act = [r["act_correct_rate"] for r in scored]
        best = max(scored, key=lambda r: r["section_correct_rate"])
        base = next((r for r in scored if r["config"] == BASELINE), None)
        verdict = {
            "n_configs": len(scored),
            "section_correct_range": [min(sec), max(sec)],
            "section_correct_spread_pp": round((max(sec) - min(sec)) * 100, 2),
            "act_correct_range": [min(act), max(act)],
            "act_correct_spread_pp": round((max(act) - min(act)) * 100, 2),
            "best_config": best["config"],
            "best_section_correct": best["section_correct_rate"],
            "baseline_config": BASELINE,
            "baseline_section_correct": base["section_correct_rate"] if base else None,
            # The question that decides whether the headline survives. A sweep
            # that moves section accuracy from ~1% to ~1% says the caveat was
            # not load-bearing; one that finds 30% says the headline is wrong.
            "any_config_materially_better": bool(max(sec) - min(sec) > 0.05),
            "seed_std_for_comparison_pp": 1.0,
        }
    payload = {"configs": rows, "verdict": verdict}
    REPORTS.mkdir(parents=True, exist_ok=True)
    (REPORTS / "sweep.json").write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    (REPORTS / "sweep.md").write_text(render(payload), encoding="utf-8")
    return payload


def render(p: dict[str, Any]) -> str:
    lines = [
        "# Hyperparameter sweep",
        "",
        "Generated by `ragft.analysis.sweep`. **Do not hand-edit.**",
        "",
        "Every headline number in this project comes from **rank 16 / lr 2e-4**, so",
        'the claim has been *"this QLoRA configuration failed at section recall"*',
        'rather than *"QLoRA fails"*. This sweep tests whether that caveat is',
        "load-bearing.",
        "",
        "One epoch per config: validation loss rises from epoch 1 on all three seeds,",
        "so configs are compared at their best point rather than their overfit one.",
        "",
        "| Config | rank | lr | trainable | val loss | correct section | correct act | fabrication |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in p["configs"]:
        mark = " ←reported" if r["config"] == BASELINE else ""
        sec = f"{r['section_correct_rate']:.1%}" if "section_correct_rate" in r else "—"
        act = f"{r['act_correct_rate']:.1%}" if "act_correct_rate" in r else "—"
        fab = f"{r['fabrication_rate']:.1%}" if "fabrication_rate" in r else "—"
        vl = f"{r['eval_loss']:.4f}" if r.get("eval_loss") is not None else "—"
        lines.append(
            f"| `{r['config']}`{mark} | {r['rank']} | {r['learning_rate']:g} | "
            f"{r['trainable_params']:,} | {vl} | **{sec}** | {act} | {fab} |"
        )

    v = p.get("verdict")
    if v:
        lo, hi = v["section_correct_range"]
        alo, ahi = v["act_correct_range"]
        lines += [
            "",
            "## Does the configuration caveat matter?",
            "",
            f"| Correct-section across {v['n_configs']} configs | {lo:.1%} to {hi:.1%} "
            f"(spread **{v['section_correct_spread_pp']} pp**) |",
            "|---|---|",
            f"| Correct-act across configs | {alo:.1%} to {ahi:.1%} "
            f"(spread {v['act_correct_spread_pp']} pp) |",
            f"| Best config | `{v['best_config']}` at {v['best_section_correct']:.1%} |",
            f"| Reported config | `{v['baseline_config']}` at "
            + (
                f"{v['baseline_section_correct']:.1%}"
                if v["baseline_section_correct"] is not None
                else "—"
            )
            + " |",
            "",
        ]
        if v["any_config_materially_better"]:
            lines += [
                "**A configuration is materially better — the headline does not survive.**",
                f"`{v['best_config']}` reaches {v['best_section_correct']:.1%} against the",
                "reported configuration. Every claim resting on section-recall failure must",
                "be rerun on that configuration before it can stand.",
                "",
            ]
        else:
            lines += [
                "**No configuration is materially better.** The spread across rank and",
                f"learning rate is {v['section_correct_spread_pp']} pp — comparable to the",
                f"~{v['seed_std_for_comparison_pp']} pp seed-to-seed noise already measured",
                "in `reports/seeds.md`, and far smaller than the ~87 pp gap between the",
                "no-retrieval and retrieval arms.",
                "",
                "So the caveat was **not** load-bearing, and the finding can be stated",
                "without it: a LoRA adapter of this size trained on 2,830 examples does not",
                "learn a ~1,090-way section mapping, and neither 4x the adapter capacity nor",
                "halving the learning rate changes that. It is a property of the task, not",
                "of one configuration.",
                "",
                "Rank 64 is the informative cell. If section recall were **capacity**-limited,",
                "4x the adapter parameters is where it would show. It does not, which points",
                "at the data rather than the adapter.",
                "",
            ]
    return "\n".join(lines)


def main() -> None:
    p = build()
    for r in p["configs"]:
        sec = f"{r.get('section_correct_rate', float('nan')):.1%}"
        print(f"  {r['config']:14s} rank={r['rank']:2d} lr={r['learning_rate']:g} correct={sec}")
    v = p.get("verdict")
    if v:
        print(
            f"\nspread {v['section_correct_spread_pp']} pp; "
            f"materially better config: {v['any_config_materially_better']}"
        )
    print(f"\nWrote {REPORTS / 'sweep.md'}")
    _ = statistics


if __name__ == "__main__":
    main()
